name: “Snyk SCA Snyk Action Test”
on:
  push:
    branches:
    - master

jobs:
  pipeline-job:
    name: "Snyk SCA Snyk Action Test"
    runs-on: ubuntu-latest 
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    steps: 
    - name: "Checkout Code"
      uses: actions/checkout@v1
    
    - name: "Install Dependancies"
      run: | 
        npm i server/

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        args: --serverity-threshhold=high