name: “Snyk Container Test”
on:
  push:
    branches:
    - master

jobs:
  pipeline-job:
    name: "Snyk SCA Test"
    runs-on: ubuntu-latest 
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    steps: 
    - name: "Checkout Code"
      uses: actions/checkout@v1

    - name: "Install and Auth Snyk"
      run: |
        sudo npm install -g snyk
        snyk auth ${SNYK_TOKEN}

    - name: "Install Dependancies"
      run: | 
        npm i server/
    # - name: "Run Snyk Test"
    #   run: |
    #     # snyk test --severity-threshold=critical --all-projects 
    #     snyk test --ignore-policy --all-projects 

    - name: "Run Snyk Container Test"
      run: |
        # snyk container test mk --severity-threshold=critical --all-projects 
        snyk container test --ignore-policy