name: “Snyk Container Test Via CLI”
on:
  push:
    branches:
    - master

jobs:
  pipeline-job:
    name: "Snyk SCA Test"
    runs-on: ubuntu-latest 
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    steps: 
    - name: "Checkout Code"
      uses: actions/checkout@v1

    - name: "Install and Auth Snyk"
      run: |
        sudo npm install -g snyk
        snyk auth ${SNYK_TOKEN}

    - name: "Install Dependancies"
      run: | 
        npm i server/

    - name: "Run Snyk Test"
      continue-on-error: true
      run: |
        snyk test  --all-projects 

    # - name: "build image"
    #   run: |
    #     docker build -t mk .   

    # - name: "Run Snyk Container Test"
    #   continue-on-error: true
    #   run: |
    #     snyk container test mk 

    #change for jenkins to run. 
     
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_AT }}

    - name: "docker hub create image"
      run: |
        docker build -t morgansnyk/mk .
    - name: "Snyk test container"
      continue-on-error: true
      run: |
        snyk container test morgansnyk/mk

    - name: "docker push"
      run: |
        sudo docker push morgansnyk/mk