name: “Snyk Container Test”
on:
  push:
    branches:
    - master

jobs:
  pipeline-job:
    name: "Snyk SCA Test"
    runs-on: ubuntu-latest 
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    steps: 
    - name: "Checkout Code"
      uses: actions/checkout@v1

    - name: "Install and Auth Snyk"
      run: |
        sudo npm install -g snyk
        snyk auth ${SNYK_TOKEN}

    - name: "Install Dependancies"
      run: | 
        npm i server/

    - name: "Run Snyk Test"
      continue-on-error: true
      run: |
        snyk test  --all-projects 

    # - name: "build image"
    #   run: |
    #     docker build -t mk .   

    # - name: "Run Snyk Container Test"
    #   continue-on-error: true
    #   run: |
    #     snyk container test mk 
     
    - name: "logon to Docker"
      run: | 
        sudo docker login -u morgansnyk -p ${{secrets.DOCKER_PASSWORD}}

    - name: "docker hub create image"
      run: |
        docker build -t morgansnyk/mk .
        
    - name: "docker run"
      run: |
        docker run morgansnyk/mk 

    - name: "docker push"
      run: |
        docker push morgansnyk/mk