name: “Snyk Code Test”
on:
  push:
    branches:
      - master

jobs:
  pipeline-job:
    name: "Snyk Code Test"
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


    steps:
      - name: Snyk Code
        on: push
        jobs:
          security:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@master
              - name: Run Snyk to check for vulnerabilities
                uses: snyk/actions/node@master
                args: --code
                env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}